# Generated by Django 4.2.3 on 2023-08-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CarCity", "0003_ad_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="picture",
            new_name="pic",
        ),
    ]
